<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class CreditOS_Report_Processing {
    private $repository,$wpdb,$parser;
    public function __construct( CreditOS_Repository $repository ) { global $wpdb;$this->repository=$repository;$this->wpdb=$wpdb;$this->parser=new CreditOS_Report_Parser();add_filter('rest_request_after_callbacks',array($this,'process_after_import'),10,3); }
    public function process_after_import($response,$handler,$request){
        if('/creditos/v1/reports/import'!==$request->get_route()||'POST'!==$request->get_method()||is_wp_error($response))return $response;
        $data=rest_get_server()->response_to_data($response,false);$id=absint($data['report_id']??0);if(!$id)return$response;
        $r=$this->wpdb->get_row($this->wpdb->prepare("SELECT id,client_id,bureau,source_attachment_id,source_format FROM {$this->wpdb->prefix}creditos_credit_reports WHERE id=%d LIMIT 1",$id),ARRAY_A);
        if(!$r||!in_array($r['source_format'],array('pdf','csv'),true))return$response;
        return $this->process_report($id,$r,$response);
    }
    public function process_report($id,array$r,$response=null){
        $client=absint($r['client_id']);$this->set_status($id,'processing',null);$path=get_attached_file(absint($r['source_attachment_id']));$parsed=$this->parser->parse($path,$r['source_format'],$r['bureau']);
        if(is_wp_error($parsed)){ $code=sanitize_key($parsed->get_error_code());$status='creditos_pdf_needs_ocr'===$code?'needs_ocr':'needs_review';$safe_errors=array('creditos_pdf_needs_ocr'=>'This PDF needs OCR or a text-readable copy before CreditOS can normalize it.');$safe_error=$safe_errors[$code]??'CreditOS could not safely normalize this report. The source file was preserved for review.';$this->set_status($id,$status,$safe_error);$this->repository->audit(get_current_user_id(),$client,'credit_report_processing_review_required','credit_report',$id,array('reason'=>$code));return $response?$this->refresh_response($response,$id,$client):false; }
        if(!empty($parsed['bureau']))$this->wpdb->update($this->wpdb->prefix.'creditos_credit_reports',array('bureau'=>sanitize_key($parsed['bureau'])),array('id'=>$id));
        $n=is_array($parsed['normalized']??null)?$parsed['normalized']:array();$counts=$this->normalized_counts($n);$total=array_sum($counts);
        /* Extraction success is not normalization success. Never show Ready For Review for an empty result. */
        if($total<1){$msg='CreditOS extracted report text but did not normalize any usable credit records. Parser refinement or reprocessing is required.';$this->set_status($id,'needs_review',$msg,'needs_review');$this->repository->audit(get_current_user_id(),$client,'credit_report_normalization_empty','credit_report',$id,array('bureau'=>$parsed['bureau']??$r['bureau'],'text_length'=>absint($parsed['text_length']??0),'counts'=>$counts));return $response?$this->refresh_response($response,$id,$client):false;}
        $this->set_status($id,'normalizing',null);$this->store_normalized($id,$client,$n);$this->set_status($id,'ready_for_review',null,'ready_for_review');$this->repository->audit(get_current_user_id(),$client,'credit_report_parser_completed','credit_report',$id,array('format'=>$r['source_format'],'bureau'=>$parsed['bureau']??$r['bureau'],'counts'=>$counts,'text_length'=>absint($parsed['text_length']??0)));return $response?$this->refresh_response($response,$id,$client):true;
    }
    private function normalized_counts(array$n){return array('tradelines'=>count((array)($n['tradelines']??array())),'collections'=>count((array)($n['collections']??array())),'inquiries'=>count((array)($n['inquiries']??array())),'personal_information'=>count((array)($n['personal_information']??array())));}
    private function set_status($id,$parser_status,$error=null,$status=null){$v=array('parser_status'=>$parser_status,'error_message'=>$error,'updated_at'=>current_time('mysql'));if($status)$v['status']=$status;$this->wpdb->update($this->wpdb->prefix.'creditos_credit_reports',$v,array('id'=>$id));}
    private function store_normalized($id,$client,array$p){$x=$this->wpdb->prefix;foreach(array('tradelines','collections','inquiries','personal_information')as$t)$this->wpdb->delete($x.'creditos_'.$t,array('report_id'=>$id,'client_id'=>$client));foreach((array)($p['tradelines']??array())as$r){if(empty($r['creditor_name']))continue;$this->wpdb->insert($x.'creditos_tradelines',array('report_id'=>$id,'client_id'=>$client,'bureau'=>sanitize_key($r['bureau']??''),'creditor_name'=>sanitize_text_field($r['creditor_name']),'account_number_masked'=>sanitize_text_field($r['account_number_masked']??''),'account_type'=>sanitize_text_field($r['account_type']??''),'opened_date'=>$this->date($r['opened_date']??''),'status'=>sanitize_text_field($r['status']??''),'balance'=>$this->money($r['balance']??null),'credit_limit'=>$this->money($r['credit_limit']??null),'past_due'=>$this->money($r['past_due']??null),'payment_status'=>sanitize_text_field($r['payment_status']??''),'date_reported'=>$this->date($r['date_reported']??''),'remarks'=>sanitize_textarea_field($r['remarks']??''),'responsibility'=>sanitize_text_field($r['responsibility']??''),'created_at'=>current_time('mysql')));}
        foreach((array)($p['collections']??array())as$r){if(empty($r['collector_name']))continue;$this->wpdb->insert($x.'creditos_collections',array('report_id'=>$id,'client_id'=>$client,'bureau'=>sanitize_key($r['bureau']??''),'collector_name'=>sanitize_text_field($r['collector_name']),'original_creditor'=>sanitize_text_field($r['original_creditor']??''),'balance'=>$this->money($r['balance']??null),'assigned_date'=>$this->date($r['assigned_date']??''),'status'=>sanitize_text_field($r['status']??''),'created_at'=>current_time('mysql')));}
        foreach((array)($p['inquiries']??array())as$r){if(empty($r['creditor_name']))continue;$this->wpdb->insert($x.'creditos_inquiries',array('report_id'=>$id,'client_id'=>$client,'bureau'=>sanitize_key($r['bureau']??''),'creditor_name'=>sanitize_text_field($r['creditor_name']),'inquiry_type'=>sanitize_key($r['inquiry_type']??''),'inquiry_date'=>$this->date($r['inquiry_date']??''),'created_at'=>current_time('mysql')));}
        foreach((array)($p['personal_information']??array())as$r){if(empty($r['info_type'])||empty($r['info_value']))continue;$this->wpdb->insert($x.'creditos_personal_information',array('report_id'=>$id,'client_id'=>$client,'bureau'=>sanitize_key($r['bureau']??''),'info_type'=>sanitize_key($r['info_type']),'info_value'=>sanitize_text_field($r['info_value']),'status'=>'reported','created_at'=>current_time('mysql')));}}
    private function refresh_response($response,$id,$client){$p=$this->wpdb->prefix;$r=$this->wpdb->get_row($this->wpdb->prepare("SELECT id,bureau,provider,report_date,imported_at,status,parser_status,source_format,source_filename,error_message FROM {$p}creditos_credit_reports WHERE id=%d AND client_id=%d LIMIT 1",$id,$client),ARRAY_A);return$r?rest_ensure_response(array('success'=>true,'report_id'=>$id,'report'=>$r)):$response;}
    private function date($v){if(!$v)return null;$t=strtotime($v);return$t?gmdate('Y-m-d',$t):null;}private function money($v){return is_numeric($v)?round((float)$v,2):null;}
}
