<?php
/** Template Name: CreditOS Account Inspector */
if(!defined('ABSPATH'))exit;if(!is_user_logged_in())auth_redirect();
$user=wp_get_current_user();$display_name=$user->display_name?:$user->user_login;
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><?php wp_head(); ?></head>
<body <?php body_class('creditos-reports-page creditos-inspector-page creditos-account-page'); ?>><?php wp_body_open(); ?>
<div class="reports-shell"><aside class="reports-sidebar"><a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="brand-mark">C</span><span>CreditOS<small>BY LEGACY X FIRM</small></span></a><nav class="reports-nav"><a href="<?php echo esc_url(home_url('/dashboard/')); ?>">← Dashboard</a><a href="<?php echo esc_url(home_url('/credit-reports/')); ?>">Report Import Center</a><a href="<?php echo esc_url(home_url('/report-inspector/')); ?>">Report Inspector</a><a class="active" href="#account">Account Review</a></nav></aside>
<div class="reports-main"><header class="reports-topbar"><div><strong>Account Inspector</strong><span>Focused tradeline review</span></div><div class="reports-user"><span><?php echo esc_html(strtoupper(substr($display_name,0,1))); ?></span><b><?php echo esc_html($display_name); ?></b></div></header>
<main class="reports-content"><section class="reports-section" id="account"><div class="section-head"><div><small>ACCOUNT INSPECTOR</small><h2>Credit account review</h2><p class="section-copy">Review this specific account, evidence, discrepancies, corrections, and review history in one focused workspace.</p></div><a id="creditos-back-report" class="reports-btn" href="<?php echo esc_url(home_url('/report-inspector/')); ?>">← Back to Report</a></div><div id="creditos-report-review" class="review-panel"><div class="empty-state">Loading account…</div></div></section></main>
<footer class="reports-footer"><div><strong>CreditOS</strong><span>Legacy X Firm Credit Operating Solutions</span></div><small>© <?php echo esc_html(gmdate('Y')); ?> Legacy X Firm.</small></footer></div></div><?php wp_footer(); ?></body></html>