<?php
/** Template Name: CreditOS Report Inspector */
if(!defined('ABSPATH'))exit;
if(!is_user_logged_in())auth_redirect();
$user=wp_get_current_user(); $display_name=$user->display_name?:$user->user_login;
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><?php wp_head(); ?></head>
<body <?php body_class('creditos-reports-page creditos-inspector-page'); ?>><?php wp_body_open(); ?>
<div class="reports-shell"><aside class="reports-sidebar"><a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="brand-mark">C</span><span>CreditOS<small>BY LEGACY X FIRM</small></span></a><nav class="reports-nav"><a href="<?php echo esc_url(home_url('/dashboard/')); ?>">← Dashboard</a><a href="<?php echo esc_url(home_url('/credit-reports/')); ?>">Report Import Center</a><a class="active" href="#review">Report Inspector</a><a href="<?php echo esc_url(home_url('/credit-reports/#saved-reviews')); ?>">Saved Reviews</a></nav></aside>
<div class="reports-main"><header class="reports-topbar"><div><strong>CreditOS Report Inspector</strong><span>Focused account review workspace</span></div><div class="reports-user"><span><?php echo esc_html(strtoupper(substr($display_name,0,1))); ?></span><b><?php echo esc_html($display_name); ?></b></div></header>
<main class="reports-content"><section class="reports-hero inspector-hero"><div><span class="phase-pill">REPORT INSPECTOR</span><h1>Review credit data in a <span>focused workspace.</span></h1><p>Select an imported report, inspect tradelines, document discrepancies and evidence, record verified corrections, and review history without crowding the Import Center.</p></div></section>
<section class="reports-section" id="history"><div class="section-head"><div><small>SELECT REPORT</small><h2>Imported reports</h2></div><button id="creditos-refresh-reports" class="reports-btn" type="button">Refresh</button></div><div id="creditos-report-list" class="report-list"><div class="empty-state">Loading report history…</div></div></section>
<section class="reports-section" id="review"><div class="section-head"><div><small>INSPECTOR WORKSPACE</small><h2>Selected report</h2></div><a class="reports-btn" href="<?php echo esc_url(home_url('/credit-reports/')); ?>">← Import Center</a></div><div id="creditos-report-review" class="review-panel"><div class="empty-state">Select a report above to begin inspection.</div></div></section></main>
<footer class="reports-footer"><div><strong>CreditOS</strong><span>Legacy X Firm Credit Operating Solutions</span></div><nav><a href="<?php echo esc_url(home_url('/credit-reports/')); ?>">Import Center</a><a href="#history">Reports</a><a href="#review">Inspector</a></nav><small>© <?php echo esc_html(gmdate('Y')); ?> Legacy X Firm.</small></footer></div></div><?php wp_footer(); ?></body></html>